Add polygon selection feature
nens/lizard-catalogue pull request #213
Opened 2020-09-14 19:06 UTC by hoanphungt

2020-09-16 07:39 UTC, hoanphungt commented on src/catalogue/components/TimeSeriesModal.tsx
> +                selectedLocations.push(location.uuid);
In this forEach function, I cannot update state of `selectedLocations` using hook function `setSelectedLocations`. During the forEach, the `selectedLocations` is not being updated synchronically so it resulted in only one last location uuid is added to `selectedLocations` at the end of the forEach.

2020-09-16 10:03 UTC, Derryrover commented on src/catalogue/components/TimeSeriesModal.tsx
> +
Hi Hoan,
As you already noted yourself this is not the preferred solution ;)
Could you try if you can first filter (see if this works with .filter instead of forEach) all locations inside the polygon? and after this filter is complete, only after this you add them to the current selection.
kr Tom

2020-09-16 10:04 UTC, Derryrover requested changes
Hi Hoan,
Looks mostly well and works, but updating the locations inside polygon could maybe be improved technically. See comment.
kr Tom

2020-09-17 10:18 UTC, hoanphungt commented on src/catalogue/components/TimeSeriesModal.tsx
> +
Yes, I changed it to use filter and then setSelectedLocations after the filter is completed and it worked well. Thanks for your suggestion :)

2020-09-21 08:12 UTC, merged